services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "54411:54411"     # host:container
    #environment:
      # Example tuning; you can pass memory, GC, profiles, etc.
      #JAVA_OPTS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:54411/health"]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped
